############################################################
# Assembler Properties
#
# Sets the default values of arguments.
# See lib.properties to set standard library path.
############################################################

# Debug [true, false]
# true:     Object files use fully-qualified names for symbols
# false:    Object files use numeric names for symbols
# Overriden to 'true' by the '-d' command-line argument
debug = false

# Optimize instruction width [true, false]
# true:     Opcodes are substituted with equivalent instructions with smaller lengths. For example,
#           ADD_RIM A, 42       84 40 42 00
#           optimizes to
#           ADD_A_I8, 42        60 42 
# false:    Opcodes are left unchanged.
# Overridden to 'true' by the -o command-line argument
# Overridden to 'false' by the -no command-line argument 
optimize_width = true

# Entry point [label name]
# Specifies the first code to be executed 
# Overridden by the -e command-line argument
entry = entry
