/*
 * WARNING: this file has been generated by
 * Hime Parser Generator 4.2.1
 */

package notsotiny.nstasm.parser;

import fr.cenotelie.hime.redist.Symbol;
import fr.cenotelie.hime.redist.lexer.Automaton;
import fr.cenotelie.hime.redist.lexer.ContextFreeLexer;

import java.io.InputStreamReader;

/**
 * Represents a lexer
 */
public class NstassemblerLexer extends ContextFreeLexer {
    /**
     * The automaton for this lexer
     */
    private static final Automaton commonAutomaton = Automaton.find(NstassemblerLexer.class, "NstassemblerLexer.bin");
    /**
     * Contains the constant IDs for the terminals for this lexer
     */
    public static class ID {
        /**
         * The unique identifier for terminal NEWLINE
         */
        public static final int TERMINAL_NEWLINE = 0x0003;
        /**
         * The unique identifier for terminal SEPARATOR
         */
        public static final int TERMINAL_SEPARATOR = 0x0006;
        /**
         * The unique identifier for terminal NAME
         */
        public static final int TERMINAL_NAME = 0x0027;
        /**
         * The unique identifier for terminal INTEGER
         */
        public static final int TERMINAL_INTEGER = 0x0028;
        /**
         * The unique identifier for terminal LOCAL
         */
        public static final int TERMINAL_LOCAL = 0x0029;
        /**
         * The unique identifier for terminal MACROLOCAL
         */
        public static final int TERMINAL_MACROLOCAL = 0x002A;
        /**
         * The unique identifier for terminal KW_REPEAT
         */
        public static final int TERMINAL_KW_REPEAT = 0x002B;
        /**
         * The unique identifier for terminal KW_MACRO
         */
        public static final int TERMINAL_KW_MACRO = 0x002C;
        /**
         * The unique identifier for terminal KW_ENDMACRO
         */
        public static final int TERMINAL_KW_ENDMACRO = 0x002D;
        /**
         * The unique identifier for terminal KW_DEFINE
         */
        public static final int TERMINAL_KW_DEFINE = 0x002E;
        /**
         * The unique identifier for terminal KW_INCLUDE
         */
        public static final int TERMINAL_KW_INCLUDE = 0x002F;
        /**
         * The unique identifier for terminal KW_LIBNAME
         */
        public static final int TERMINAL_KW_LIBNAME = 0x0030;
        /**
         * The unique identifier for terminal KW_ORG
         */
        public static final int TERMINAL_KW_ORG = 0x0031;
        /**
         * The unique identifier for terminal KW_NLO
         */
        public static final int TERMINAL_KW_NLO = 0x0032;
        /**
         * The unique identifier for terminal KW_PRIVILEGED
         */
        public static final int TERMINAL_KW_PRIVILEGED = 0x0033;
        /**
         * The unique identifier for terminal KW_BYTE
         */
        public static final int TERMINAL_KW_BYTE = 0x0034;
        /**
         * The unique identifier for terminal KW_WORD
         */
        public static final int TERMINAL_KW_WORD = 0x0035;
        /**
         * The unique identifier for terminal KW_PTR
         */
        public static final int TERMINAL_KW_PTR = 0x0036;
        /**
         * The unique identifier for terminal KW_DB
         */
        public static final int TERMINAL_KW_DB = 0x0037;
        /**
         * The unique identifier for terminal KW_DW
         */
        public static final int TERMINAL_KW_DW = 0x0038;
        /**
         * The unique identifier for terminal KW_DP
         */
        public static final int TERMINAL_KW_DP = 0x0039;
        /**
         * The unique identifier for terminal KW_RESB
         */
        public static final int TERMINAL_KW_RESB = 0x003A;
        /**
         * The unique identifier for terminal KW_RESW
         */
        public static final int TERMINAL_KW_RESW = 0x003B;
        /**
         * The unique identifier for terminal KW_RESP
         */
        public static final int TERMINAL_KW_RESP = 0x003C;
        /**
         * The unique identifier for terminal KW_AS
         */
        public static final int TERMINAL_KW_AS = 0x003D;
        /**
         * The unique identifier for terminal OP_OR
         */
        public static final int TERMINAL_OP_OR = 0x003E;
        /**
         * The unique identifier for terminal OP_XOR
         */
        public static final int TERMINAL_OP_XOR = 0x003F;
        /**
         * The unique identifier for terminal OP_AND
         */
        public static final int TERMINAL_OP_AND = 0x0040;
        /**
         * The unique identifier for terminal OP_SHL
         */
        public static final int TERMINAL_OP_SHL = 0x0041;
        /**
         * The unique identifier for terminal OP_SHR
         */
        public static final int TERMINAL_OP_SHR = 0x0042;
        /**
         * The unique identifier for terminal OP_SAR
         */
        public static final int TERMINAL_OP_SAR = 0x0043;
        /**
         * The unique identifier for terminal OP_ADD
         */
        public static final int TERMINAL_OP_ADD = 0x0044;
        /**
         * The unique identifier for terminal OP_SUB
         */
        public static final int TERMINAL_OP_SUB = 0x0045;
        /**
         * The unique identifier for terminal OP_MUL
         */
        public static final int TERMINAL_OP_MUL = 0x0046;
        /**
         * The unique identifier for terminal OP_DIV
         */
        public static final int TERMINAL_OP_DIV = 0x0047;
        /**
         * The unique identifier for terminal OP_MOD
         */
        public static final int TERMINAL_OP_MOD = 0x0048;
        /**
         * The unique identifier for terminal OP_NOT
         */
        public static final int TERMINAL_OP_NOT = 0x0049;
        /**
         * The unique identifier for terminal OP_CREL
         */
        public static final int TERMINAL_OP_CREL = 0x004A;
        /**
         * The unique identifier for terminal OP_PREL
         */
        public static final int TERMINAL_OP_PREL = 0x004B;
        /**
         * The unique identifier for terminal OP_SREL
         */
        public static final int TERMINAL_OP_SREL = 0x004C;
        /**
         * The unique identifier for terminal REGISTER
         */
        public static final int TERMINAL_REGISTER = 0x0055;
        /**
         * The unique identifier for terminal OPCODE
         */
        public static final int TERMINAL_OPCODE = 0x0056;
        /**
         * The unique identifier for terminal STRING
         */
        public static final int TERMINAL_STRING = 0x0057;
    }
    /**
     * Contains the constant IDs for the contexts for this lexer
     */
    public static class Context {
        /**
         * The unique identifier for the default context
         */
        public static final int DEFAULT = 0;
    }
    /**
     * The collection of terminals matched by this lexer
     *
     * The terminals are in an order consistent with the automaton,
     * so that terminal indices in the automaton can be used to retrieve the terminals in this table
     */
    private static final Symbol[] terminals = {
        new Symbol(0x0001, "ε"),
        new Symbol(0x0002, "$"),
        new Symbol(0x0003, "NEWLINE"),
        new Symbol(0x0006, "SEPARATOR"),
        new Symbol(0x0027, "NAME"),
        new Symbol(0x0028, "INTEGER"),
        new Symbol(0x0029, "LOCAL"),
        new Symbol(0x002A, "MACROLOCAL"),
        new Symbol(0x002B, "KW_REPEAT"),
        new Symbol(0x002C, "KW_MACRO"),
        new Symbol(0x002D, "KW_ENDMACRO"),
        new Symbol(0x002E, "KW_DEFINE"),
        new Symbol(0x002F, "KW_INCLUDE"),
        new Symbol(0x0030, "KW_LIBNAME"),
        new Symbol(0x0031, "KW_ORG"),
        new Symbol(0x0032, "KW_NLO"),
        new Symbol(0x0033, "KW_PRIVILEGED"),
        new Symbol(0x0034, "KW_BYTE"),
        new Symbol(0x0035, "KW_WORD"),
        new Symbol(0x0036, "KW_PTR"),
        new Symbol(0x0037, "KW_DB"),
        new Symbol(0x0038, "KW_DW"),
        new Symbol(0x0039, "KW_DP"),
        new Symbol(0x003A, "KW_RESB"),
        new Symbol(0x003B, "KW_RESW"),
        new Symbol(0x003C, "KW_RESP"),
        new Symbol(0x003D, "KW_AS"),
        new Symbol(0x003E, "OP_OR"),
        new Symbol(0x003F, "OP_XOR"),
        new Symbol(0x0040, "OP_AND"),
        new Symbol(0x0041, "OP_SHL"),
        new Symbol(0x0042, "OP_SHR"),
        new Symbol(0x0043, "OP_SAR"),
        new Symbol(0x0044, "OP_ADD"),
        new Symbol(0x0045, "OP_SUB"),
        new Symbol(0x0046, "OP_MUL"),
        new Symbol(0x0047, "OP_DIV"),
        new Symbol(0x0048, "OP_MOD"),
        new Symbol(0x0049, "OP_NOT"),
        new Symbol(0x004A, "OP_CREL"),
        new Symbol(0x004B, "OP_PREL"),
        new Symbol(0x004C, "OP_SREL"),
        new Symbol(0x0055, "REGISTER"),
        new Symbol(0x0056, "OPCODE"),
        new Symbol(0x0057, "STRING"),
        new Symbol(0x0075, ":"),
        new Symbol(0x0078, "("),
        new Symbol(0x0079, ","),
        new Symbol(0x007C, ")"),
        new Symbol(0x007F, "["),
        new Symbol(0x0080, "]") };
    /**
     * Initializes a new instance of the lexer
     *
     * @param input The lexer's input
     */
    public NstassemblerLexer(String input) {
        super(commonAutomaton, terminals, 0x0006, input);
    }
    /**
     * Initializes a new instance of the lexer
     *
     * @param input The lexer's input
     */
    public NstassemblerLexer(InputStreamReader input) {
        super(commonAutomaton, terminals, 0x0006, input);
    }
}
