/*
 * WARNING: this file has been generated by
 * Hime Parser Generator 4.2.1
 */

package notsotiny.nstasm.parser;

import fr.cenotelie.hime.redist.ASTNode;
import fr.cenotelie.hime.redist.ParseResult;
import fr.cenotelie.hime.redist.SemanticAction;
import fr.cenotelie.hime.redist.SemanticBody;
import fr.cenotelie.hime.redist.Symbol;
import fr.cenotelie.hime.redist.parsers.InitializationException;
import fr.cenotelie.hime.redist.parsers.LRkAutomaton;
import fr.cenotelie.hime.redist.parsers.LRkParser;

import java.util.Map;

/**
 * Represents a parser
 */
public class NstassemblerParser extends LRkParser {
    /**
     * The automaton for this parser
     */
    private static final LRkAutomaton COMMON_AUTOMATON = LRkAutomaton.find(NstassemblerParser.class, "NstassemblerParser.bin");
    /**
     * Contains the constant IDs for the variables and virtuals in this parser
     */
    public static class ID {
        /**
         * The unique identifier for variable program
         */
        public static final int VARIABLE_PROGRAM = 0x0058;
        /**
         * The unique identifier for variable top_level
         */
        public static final int VARIABLE_TOP_LEVEL = 0x0059;
        /**
         * The unique identifier for variable macro
         */
        public static final int VARIABLE_MACRO = 0x005A;
        /**
         * The unique identifier for variable def_macro
         */
        public static final int VARIABLE_DEF_MACRO = 0x005B;
        /**
         * The unique identifier for variable single_macro
         */
        public static final int VARIABLE_SINGLE_MACRO = 0x005C;
        /**
         * The unique identifier for variable multi_macro
         */
        public static final int VARIABLE_MULTI_MACRO = 0x005D;
        /**
         * The unique identifier for variable macro_head
         */
        public static final int VARIABLE_MACRO_HEAD = 0x005E;
        /**
         * The unique identifier for variable line
         */
        public static final int VARIABLE_LINE = 0x005F;
        /**
         * The unique identifier for variable label
         */
        public static final int VARIABLE_LABEL = 0x0060;
        /**
         * The unique identifier for variable directive
         */
        public static final int VARIABLE_DIRECTIVE = 0x0061;
        /**
         * The unique identifier for variable statement
         */
        public static final int VARIABLE_STATEMENT = 0x0062;
        /**
         * The unique identifier for variable initialized
         */
        public static final int VARIABLE_INITIALIZED = 0x0063;
        /**
         * The unique identifier for variable uninitialized
         */
        public static final int VARIABLE_UNINITIALIZED = 0x0064;
        /**
         * The unique identifier for variable instruction
         */
        public static final int VARIABLE_INSTRUCTION = 0x0065;
        /**
         * The unique identifier for variable arg
         */
        public static final int VARIABLE_ARG = 0x0066;
        /**
         * The unique identifier for variable memory
         */
        public static final int VARIABLE_MEMORY = 0x0067;
        /**
         * The unique identifier for variable expression
         */
        public static final int VARIABLE_EXPRESSION = 0x0068;
        /**
         * The unique identifier for variable exp_or
         */
        public static final int VARIABLE_EXP_OR = 0x0069;
        /**
         * The unique identifier for variable exp_xor
         */
        public static final int VARIABLE_EXP_XOR = 0x006A;
        /**
         * The unique identifier for variable exp_and
         */
        public static final int VARIABLE_EXP_AND = 0x006B;
        /**
         * The unique identifier for variable exp_shift
         */
        public static final int VARIABLE_EXP_SHIFT = 0x006C;
        /**
         * The unique identifier for variable exp_add
         */
        public static final int VARIABLE_EXP_ADD = 0x006D;
        /**
         * The unique identifier for variable exp_mul
         */
        public static final int VARIABLE_EXP_MUL = 0x006E;
        /**
         * The unique identifier for variable exp_unary
         */
        public static final int VARIABLE_EXP_UNARY = 0x006F;
        /**
         * The unique identifier for variable exp_val
         */
        public static final int VARIABLE_EXP_VAL = 0x0070;
        /**
         * The unique identifier for variable relative
         */
        public static final int VARIABLE_RELATIVE = 0x0071;
        /**
         * The unique identifier for variable invocation
         */
        public static final int VARIABLE_INVOCATION = 0x0072;
        /**
         * The unique identifier for variable identifier
         */
        public static final int VARIABLE_IDENTIFIER = 0x0073;
    }
    /**
     * The collection of variables matched by this parser
     *
     * The variables are in an order consistent with the automaton,
     * so that variable indices in the automaton can be used to retrieve the variables in this table
     */
    private static final Symbol[] variables = {
        new Symbol(0x0058, "program"), 
        new Symbol(0x0059, "top_level"), 
        new Symbol(0x005A, "macro"), 
        new Symbol(0x005B, "def_macro"), 
        new Symbol(0x005C, "single_macro"), 
        new Symbol(0x005D, "multi_macro"), 
        new Symbol(0x005E, "macro_head"), 
        new Symbol(0x005F, "line"), 
        new Symbol(0x0060, "label"), 
        new Symbol(0x0061, "directive"), 
        new Symbol(0x0062, "statement"), 
        new Symbol(0x0063, "initialized"), 
        new Symbol(0x0064, "uninitialized"), 
        new Symbol(0x0065, "instruction"), 
        new Symbol(0x0066, "arg"), 
        new Symbol(0x0067, "memory"), 
        new Symbol(0x0068, "expression"), 
        new Symbol(0x0069, "exp_or"), 
        new Symbol(0x006A, "exp_xor"), 
        new Symbol(0x006B, "exp_and"), 
        new Symbol(0x006C, "exp_shift"), 
        new Symbol(0x006D, "exp_add"), 
        new Symbol(0x006E, "exp_mul"), 
        new Symbol(0x006F, "exp_unary"), 
        new Symbol(0x0070, "exp_val"), 
        new Symbol(0x0071, "relative"), 
        new Symbol(0x0072, "invocation"), 
        new Symbol(0x0073, "identifier"), 
        new Symbol(0x0074, "__V116"), 
        new Symbol(0x0076, "__V118"), 
        new Symbol(0x0077, "__V119"), 
        new Symbol(0x007A, "__V122"), 
        new Symbol(0x007B, "__V123"), 
        new Symbol(0x007D, "__V125"), 
        new Symbol(0x007E, "__V126"), 
        new Symbol(0x0081, "__V129"), 
        new Symbol(0x0082, "__V130"), 
        new Symbol(0x0083, "__VAxiom") };
    /**
     * The collection of virtuals matched by this parser
     *
     * The virtuals are in an order consistent with the automaton,
     * so that virtual indices in the automaton can be used to retrieve the virtuals in this table
     */
    private static final Symbol[] virtuals = {
 };
    /**
     * Initializes a new instance of the parser
     *
     * @param lexer The input lexer
     */
    public NstassemblerParser(NstassemblerLexer lexer) {
        super(COMMON_AUTOMATON, variables, virtuals, null, lexer);
    }

    /*
     * Visitor interface
     */
    public static class Visitor {
        public void onTerminalNewline(ASTNode node) {}
        public void onTerminalSeparator(ASTNode node) {}
        public void onTerminalName(ASTNode node) {}
        public void onTerminalInteger(ASTNode node) {}
        public void onTerminalLocal(ASTNode node) {}
        public void onTerminalMacrolocal(ASTNode node) {}
        public void onTerminalKwRepeat(ASTNode node) {}
        public void onTerminalKwMacro(ASTNode node) {}
        public void onTerminalKwEndmacro(ASTNode node) {}
        public void onTerminalKwDefine(ASTNode node) {}
        public void onTerminalKwInclude(ASTNode node) {}
        public void onTerminalKwLibname(ASTNode node) {}
        public void onTerminalKwOrg(ASTNode node) {}
        public void onTerminalKwNlo(ASTNode node) {}
        public void onTerminalKwPrivileged(ASTNode node) {}
        public void onTerminalKwByte(ASTNode node) {}
        public void onTerminalKwWord(ASTNode node) {}
        public void onTerminalKwPtr(ASTNode node) {}
        public void onTerminalKwDb(ASTNode node) {}
        public void onTerminalKwDw(ASTNode node) {}
        public void onTerminalKwDp(ASTNode node) {}
        public void onTerminalKwResb(ASTNode node) {}
        public void onTerminalKwResw(ASTNode node) {}
        public void onTerminalKwResp(ASTNode node) {}
        public void onTerminalKwAs(ASTNode node) {}
        public void onTerminalOpOr(ASTNode node) {}
        public void onTerminalOpXor(ASTNode node) {}
        public void onTerminalOpAnd(ASTNode node) {}
        public void onTerminalOpShl(ASTNode node) {}
        public void onTerminalOpShr(ASTNode node) {}
        public void onTerminalOpSar(ASTNode node) {}
        public void onTerminalOpAdd(ASTNode node) {}
        public void onTerminalOpSub(ASTNode node) {}
        public void onTerminalOpMul(ASTNode node) {}
        public void onTerminalOpDiv(ASTNode node) {}
        public void onTerminalOpMod(ASTNode node) {}
        public void onTerminalOpNot(ASTNode node) {}
        public void onTerminalOpCrel(ASTNode node) {}
        public void onTerminalOpPrel(ASTNode node) {}
        public void onTerminalOpSrel(ASTNode node) {}
        public void onTerminalRegister(ASTNode node) {}
        public void onTerminalOpcode(ASTNode node) {}
        public void onTerminalString(ASTNode node) {}
        public void onVariableProgram(ASTNode node) {}
        public void onVariableTopLevel(ASTNode node) {}
        public void onVariableMacro(ASTNode node) {}
        public void onVariableDefMacro(ASTNode node) {}
        public void onVariableSingleMacro(ASTNode node) {}
        public void onVariableMultiMacro(ASTNode node) {}
        public void onVariableMacroHead(ASTNode node) {}
        public void onVariableLine(ASTNode node) {}
        public void onVariableLabel(ASTNode node) {}
        public void onVariableDirective(ASTNode node) {}
        public void onVariableStatement(ASTNode node) {}
        public void onVariableInitialized(ASTNode node) {}
        public void onVariableUninitialized(ASTNode node) {}
        public void onVariableInstruction(ASTNode node) {}
        public void onVariableArg(ASTNode node) {}
        public void onVariableMemory(ASTNode node) {}
        public void onVariableExpression(ASTNode node) {}
        public void onVariableExpOr(ASTNode node) {}
        public void onVariableExpXor(ASTNode node) {}
        public void onVariableExpAnd(ASTNode node) {}
        public void onVariableExpShift(ASTNode node) {}
        public void onVariableExpAdd(ASTNode node) {}
        public void onVariableExpMul(ASTNode node) {}
        public void onVariableExpUnary(ASTNode node) {}
        public void onVariableExpVal(ASTNode node) {}
        public void onVariableRelative(ASTNode node) {}
        public void onVariableInvocation(ASTNode node) {}
        public void onVariableIdentifier(ASTNode node) {}
    }

    /*
     * Walk the AST of a result using a visitor
     *
     * @param result  The parse result
     * @param visitor The visitor to use
     */
    public static void visit(ParseResult result, Visitor visitor) {
        visitASTNode(result.getRoot(), visitor);
    }

    /*
     * Walk the sub-AST from the specified node using a visitor
     *
     * @param node    The AST node to start from
     * @param visitor The visitor to use
     */
    public static void visitASTNode(ASTNode node, Visitor visitor) {
        for (ASTNode child : node.getChildren())
            visitASTNode(child, visitor);
        switch(node.getSymbol().getID()) {
            case 0x0003: visitor.onTerminalNewline(node); break;
            case 0x0006: visitor.onTerminalSeparator(node); break;
            case 0x0027: visitor.onTerminalName(node); break;
            case 0x0028: visitor.onTerminalInteger(node); break;
            case 0x0029: visitor.onTerminalLocal(node); break;
            case 0x002A: visitor.onTerminalMacrolocal(node); break;
            case 0x002B: visitor.onTerminalKwRepeat(node); break;
            case 0x002C: visitor.onTerminalKwMacro(node); break;
            case 0x002D: visitor.onTerminalKwEndmacro(node); break;
            case 0x002E: visitor.onTerminalKwDefine(node); break;
            case 0x002F: visitor.onTerminalKwInclude(node); break;
            case 0x0030: visitor.onTerminalKwLibname(node); break;
            case 0x0031: visitor.onTerminalKwOrg(node); break;
            case 0x0032: visitor.onTerminalKwNlo(node); break;
            case 0x0033: visitor.onTerminalKwPrivileged(node); break;
            case 0x0034: visitor.onTerminalKwByte(node); break;
            case 0x0035: visitor.onTerminalKwWord(node); break;
            case 0x0036: visitor.onTerminalKwPtr(node); break;
            case 0x0037: visitor.onTerminalKwDb(node); break;
            case 0x0038: visitor.onTerminalKwDw(node); break;
            case 0x0039: visitor.onTerminalKwDp(node); break;
            case 0x003A: visitor.onTerminalKwResb(node); break;
            case 0x003B: visitor.onTerminalKwResw(node); break;
            case 0x003C: visitor.onTerminalKwResp(node); break;
            case 0x003D: visitor.onTerminalKwAs(node); break;
            case 0x003E: visitor.onTerminalOpOr(node); break;
            case 0x003F: visitor.onTerminalOpXor(node); break;
            case 0x0040: visitor.onTerminalOpAnd(node); break;
            case 0x0041: visitor.onTerminalOpShl(node); break;
            case 0x0042: visitor.onTerminalOpShr(node); break;
            case 0x0043: visitor.onTerminalOpSar(node); break;
            case 0x0044: visitor.onTerminalOpAdd(node); break;
            case 0x0045: visitor.onTerminalOpSub(node); break;
            case 0x0046: visitor.onTerminalOpMul(node); break;
            case 0x0047: visitor.onTerminalOpDiv(node); break;
            case 0x0048: visitor.onTerminalOpMod(node); break;
            case 0x0049: visitor.onTerminalOpNot(node); break;
            case 0x004A: visitor.onTerminalOpCrel(node); break;
            case 0x004B: visitor.onTerminalOpPrel(node); break;
            case 0x004C: visitor.onTerminalOpSrel(node); break;
            case 0x0055: visitor.onTerminalRegister(node); break;
            case 0x0056: visitor.onTerminalOpcode(node); break;
            case 0x0057: visitor.onTerminalString(node); break;
            case 0x0058: visitor.onVariableProgram(node); break;
            case 0x0059: visitor.onVariableTopLevel(node); break;
            case 0x005A: visitor.onVariableMacro(node); break;
            case 0x005B: visitor.onVariableDefMacro(node); break;
            case 0x005C: visitor.onVariableSingleMacro(node); break;
            case 0x005D: visitor.onVariableMultiMacro(node); break;
            case 0x005E: visitor.onVariableMacroHead(node); break;
            case 0x005F: visitor.onVariableLine(node); break;
            case 0x0060: visitor.onVariableLabel(node); break;
            case 0x0061: visitor.onVariableDirective(node); break;
            case 0x0062: visitor.onVariableStatement(node); break;
            case 0x0063: visitor.onVariableInitialized(node); break;
            case 0x0064: visitor.onVariableUninitialized(node); break;
            case 0x0065: visitor.onVariableInstruction(node); break;
            case 0x0066: visitor.onVariableArg(node); break;
            case 0x0067: visitor.onVariableMemory(node); break;
            case 0x0068: visitor.onVariableExpression(node); break;
            case 0x0069: visitor.onVariableExpOr(node); break;
            case 0x006A: visitor.onVariableExpXor(node); break;
            case 0x006B: visitor.onVariableExpAnd(node); break;
            case 0x006C: visitor.onVariableExpShift(node); break;
            case 0x006D: visitor.onVariableExpAdd(node); break;
            case 0x006E: visitor.onVariableExpMul(node); break;
            case 0x006F: visitor.onVariableExpUnary(node); break;
            case 0x0070: visitor.onVariableExpVal(node); break;
            case 0x0071: visitor.onVariableRelative(node); break;
            case 0x0072: visitor.onVariableInvocation(node); break;
            case 0x0073: visitor.onVariableIdentifier(node); break;
        }
    }
}
